apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- backup-configmap.yaml
- backup.yaml 
patches:
  - path: deployment.yaml

namePrefix: production-
images:
  - name: PROJECT/IMAGE
    newName: ""