apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
namePrefix: staging-

images:
- name: todo-app
  newName: gcr.io/gke-dwe/todo-app
  newTag: main-1b84e6171bd1c0fadcb0740cee46c60e26728013
- name: todo-backend
  newName: gcr.io/gke-dwe/todo-backend
  newTag: main-1b84e6171bd1c0fadcb0740cee46c60e26728013
- name: todo-broadcaster
  newName: gcr.io/gke-dwe/todo-broadcaster
  newTag: main-1b84e6171bd1c0fadcb0740cee46c60e26728013
