apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- secret.yaml
namePrefix: staging-

images:
- name: todo-app
  newName: gcr.io/gke-dwe/todo-app
  newTag: main-79e99bfb3fa4302b5e27b553613647591c16021f
- name: todo-backend
  newName: gcr.io/gke-dwe/todo-backend
  newTag: main-79e99bfb3fa4302b5e27b553613647591c16021f
- name: todo-broadcaster
  newName: gcr.io/gke-dwe/todo-broadcaster
  newTag: main-79e99bfb3fa4302b5e27b553613647591c16021f
