apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
namePrefix: staging-

images:
  - name: todo-backend
    newName: ""
  - name: todo-app
    newName: ""
  - name: todo-broadcaster
    newName: ""