apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- secret.yaml
namePrefix: staging-

images:
- name: todo-app
  newName: gcr.io/gke-dwe/todo-app
  newTag: main-b6ba2af42e9918a3f11c7c3b000d1b574e96913f
- name: todo-backend
  newName: gcr.io/gke-dwe/todo-backend
  newTag: main-b6ba2af42e9918a3f11c7c3b000d1b574e96913f
- name: todo-broadcaster
  newName: gcr.io/gke-dwe/todo-broadcaster
  newTag: main-b6ba2af42e9918a3f11c7c3b000d1b574e96913f
