apiVersion: v1
kind: Secret
metadata:
  name: todo-postgres-secret
  labels:
    app: postgres
stringData:
  DATABASE_URL: staging-postgres://ps_user:strongpass0000@postgres:5432/ps_db?sslmode=disable

